apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  strategy:
      type: Recreate
  template:
    metadata:
      name: mavenwebpod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - image: satishrekha/maven-web-app:VERSION
        name: mavenwebappcontainer
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mavenservice
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
    - port: 80
      targetPort: 8080
